name: Add new issues and PRs to @jdhoffa's Maintenance Responsibilities GH Project

on:
  issues:
    types:
      - opened
      - transferred
  pull_request:
    branches: [main]
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/RMI-PACTA/projects/12
          github-token: ${{ secrets.PAT_ADD_ISSUES_TO_PROJECT }}
